from __future__ import annotations

import json

from pipeline_lib import cfg, ensure_dirs, write_json
from modeling_lib import TARGET_SPECIES, load_training_samples, species_dir


def load_json(path, default):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def species_summary(species_id: str) -> dict:
    data = load_training_samples(species_id)
    metadata = load_json(species_dir(species_id) / "model_metadata.json", {})
    metrics = load_json(cfg.DATA / "processed" / "metrics" / f"{species_id}_metrics.json", {})
    prediction_summary = load_json(cfg.DATA / "processed" / "predictions" / "real_model_prediction_summary.json", {})
    presence = int((data["label"].astype(int) == 1).sum()) if not data.empty and "label" in data.columns else 0
    background = int((data["label"].astype(int) == 0).sum()) if not data.empty and "label" in data.columns else 0
    return {
        "species_id": species_id,
        "common_name": cfg.SPECIES_CONFIG[species_id]["common_name"],
        "training_samples": int(len(data)),
        "presence": presence,
        "background": background,
        "model_status": metadata.get("status", "not_trained"),
        "selected_model": metadata.get("model_type"),
        "feature_set_name": metadata.get("feature_set_name"),
        "confidence_level": metadata.get("confidence_level", "Rule-based only"),
        "reason": metadata.get("reason"),
        "metrics_status": metrics.get("status"),
        "prediction_status": prediction_summary.get("status"),
    }


def write_reports(summary: dict) -> None:
    trained = [s for s in summary["species"] if s["model_status"] == "selected"]
    blocked = [s for s in summary["species"] if s["model_status"] != "selected"]
    lines = [
        "# Model Training Summary",
        "",
        "This report covers the first real-model training workflow for Sydney Offshore Pelagic AI Map.",
        "",
        "The modelling target is relative habitat suitability / hotspot score. It is not exact fish location, guaranteed fish school, live GPS, or true catch probability.",
        "",
        "## Executive Summary",
        "",
        f"Trained species: {len(trained)}",
        f"Rule-based / blocked species: {len(blocked)}",
        "",
    ]
    if not trained:
        lines.append("No real habitat suitability models were trained because the prepared training datasets contain zero date-aligned samples. Required MUR SST feature grids are still unavailable.")
    lines.extend(["", "## Species Status", "", "| Species | Presence | Background | Status | Selected Model | Confidence | Reason |", "| --- | ---: | ---: | --- | --- | --- | --- |"])
    for item in summary["species"]:
        lines.append(
            f"| {item['species_id']} | {item['presence']} | {item['background']} | {item['model_status']} | {item.get('selected_model') or ''} | {item.get('confidence_level') or ''} | {item.get('reason') or ''} |"
        )
    lines.extend(
        [
            "",
            "## Dataset Summary",
            "",
            "The training files were inspected under `data/processed/training/`. Each current file has headers but zero rows, because the preparation pipeline refused to use synthetic/proxy SST grids for real training.",
            "",
            "## Model Comparison",
            "",
            "Baseline model code is implemented for Logistic Regression, Random Forest, and HistGradientBoostingClassifier. Optional LightGBM/XGBoost are attempted only if installed. No candidate could be fit without non-empty presence/background samples.",
            "",
            "## Automatic Improvement Summary",
            "",
            "The training pipeline is ready to try feature sets, background ratios, class weighting, Random Forest tuning, and HistGradientBoosting tuning. These loops were not run because there is no valid training matrix yet.",
            "",
            "## Ecological Interpretation",
            "",
            "No feature importance is reported until a real model is trained. When trained, interpretation must focus on SST, fronts, shelf-break/depth, seasonality, structure, currents and chlorophyll where available.",
            "",
            "## Prediction Outputs",
            "",
            "No real-model Sydney heatmap was generated in this run. Existing older prediction files should be treated as previous proxy/demo artifacts unless regenerated by `pipelines/17_predict_sydney_heatmap.py` after real training.",
            "",
            "## Limitations",
            "",
            "- Occurrence data is presence-only.",
            "- Background samples are pseudo-absence / available environment, not confirmed absence.",
            "- There is no catch/no-catch effort dataset yet.",
            "- The model target is relative habitat suitability, not exact fish location.",
            "- Local Sydney performance depends on better local catch/tag data and reliable oceanographic feature extraction.",
            "",
            "## Recommended Next Steps",
            "",
            "1. Implement reliable NASA MUR SST subset download for occurrence dates.",
            "2. Add GEBCO NSW/East Coast subset features.",
            "3. Re-run `python pipelines/run_prepare_training_data.py`.",
            "4. Re-run `python pipelines/run_train_models.py`.",
            "5. Add Copernicus currents/chlorophyll after SST + bathymetry are stable.",
        ]
    )
    text = "\n".join(lines)
    (cfg.DATA / "processed" / "reports" / "MODEL_TRAINING_SUMMARY.md").write_text(text, encoding="utf-8")
    (cfg.ROOT / "docs" / "MODEL_TRAINING_REPORT.md").write_text(text, encoding="utf-8")


def main() -> None:
    ensure_dirs()
    summary = {
        "project": "Sydney Offshore Pelagic AI Map",
        "target": "relative habitat suitability / pelagic hotspot score",
        "not_claimed": ["exact fish location", "guaranteed fish school", "live fish GPS", "true catch probability"],
        "species": [species_summary(species_id) for species_id in TARGET_SPECIES],
    }
    write_json(cfg.DATA / "processed" / "reports" / "model_training_summary.json", summary)
    write_reports(summary)
    print(summary)


if __name__ == "__main__":
    main()
